# Generated by Django 4.1.1 on 2022-11-22 15:31

import fernet_fields.fields

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("otp_static", "0002_throttling"),
    ]

    operations = [
        migrations.AddField(
            model_name="statictoken",
            name="encrypted_token",
            field=fernet_fields.fields.EncryptedCharField(max_length=250, default=""),
        ),
    ]
