# Generated by Django 4.1.1 on 2022-11-22 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("otp_static", "0005_remove_statictoken_token"),
    ]

    operations = [
        migrations.RenameField(
            model_name="statictoken",
            old_name="encrypted_token",
            new_name="token",
        ),
    ]
