# Generated by Django 4.1.1 on 2022-11-22 15:32

import fernet_fields.fields

from django.db import migrations

import django_otp.plugins.otp_totp.models


class Migration(migrations.Migration):

    dependencies = [
        ("otp_totp", "0002_auto_20190420_0723"),
    ]

    operations = [
        migrations.AddField(
            model_name="totpdevice",
            name="encrypted_key",
            field=fernet_fields.fields.EncryptedCharField(
                default=django_otp.plugins.otp_totp.models.default_key,
                help_text="A hex-encoded secret key of up to 40 bytes.",
                max_length=250,
                validators=[django_otp.plugins.otp_totp.models.key_validator],
            ),
        ),
    ]
