# Generated by Django 4.1.1 on 2022-11-22 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("otp_totp", "0005_remove_totpdevice_key"),
    ]

    operations = [
        migrations.RenameField(
            model_name="totpdevice",
            old_name="encrypted_key",
            new_name="key",
        ),
    ]
